# Generated by Django 2.1 on 2018-09-03 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_reg_no', models.CharField(max_length=20, verbose_name='Registration Number')),
                ('car_model', models.CharField(choices=[('2008', '2008'), ('206', '206'), ('206 CC', '206 CC'), ('207 Sedan', '207 Sedan'), ('207 CC', '207 CC'), ('208', '208'), ('208 GTi', '208 GTi'), ('3008', '3008'), ('305', '305'), ('306', '306'), ('307', '307'), ('307 SW', '307 SW'), ('308', '308'), ('308 CC', '308 CC'), ('405', '405'), ('406', '406'), ('407', '407'), ('407 SW', '407 SW'), ('408', '408'), ('5008', '5008'), ('504', '504'), ('505', '505'), ('508', '508'), ('508 SW', '508 SW'), ('607', '607'), ('807', '807'), ('Partner', 'Partner'), ('RCZ', 'RCZ'), ('Traveller', 'Traveller')], max_length=20, verbose_name='Model')),
                ('car_primary_sec', models.SmallIntegerField(blank=True, choices=[(1, 'Primary'), (2, 'Secondary')], null=True, verbose_name='Primary/Secondary Car')),
                ('car_status', models.BooleanField(default=True, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('member_email', models.EmailField(max_length=200, verbose_name='Email Address')),
                ('member_phone', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('member_since', models.DateField(blank=True, null=True)),
                ('member_birthdate', models.DateField(blank=True, null=True, verbose_name='Your Birthdate')),
                ('member_address_state', models.CharField(blank=True, choices=[('JH', 'Johor'), ('KH', 'Kedah'), ('KN', 'Kelantan'), ('KL', 'Kuala Lumpur'), ('LA', 'Labuan'), ('ME', 'Melaka'), ('NS', 'Negeri Sembilan'), ('PH', 'Pahang'), ('PK', 'Perak'), ('PL', 'Perlis'), ('PG', 'Pulau Pinang'), ('PJ', 'Putrajaya'), ('SA', 'Sabah'), ('SK', 'Sarawak'), ('SL', 'Selangor'), ('TE', 'Terengganu')], max_length=2, null=True, verbose_name='Current Location (State)')),
                ('member_address_postcode', models.CharField(blank=True, max_length=5, null=True, verbose_name='Postcode')),
                ('member_on_chat', models.BooleanField(default=True, verbose_name='Would you like to be added to our WhatsApp Group?')),
                ('member_source', models.CharField(blank=True, choices=[('FB', 'Facebook'), ('TW', 'Twitter'), ('SC', 'Service Center'), ('IN', 'Instagram'), ('RE', 'Referral'), ('WO', 'Word of Mouth'), ('OT', 'Other')], max_length=2, null=True, verbose_name='Where did you hear about us?')),
                ('member_expiry_date', models.DateField(blank=True, null=True)),
                ('member_pdpa_accepted', models.BooleanField(default=False, verbose_name='By selecting "Yes" you agree to the PCM PDPA policy.')),
                ('member_status', models.BooleanField(default=True, verbose_name='Status')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, verbose_name='Payment Date')),
                ('payment_amount', models.IntegerField(verbose_name='Payment Amount')),
                ('payment_type', models.CharField(choices=[('1', 'New'), ('2', 'Renewal'), ('3', 'Supplementary')], max_length=1, verbose_name='Payment For')),
                ('payment_receipt_image', models.FileField(upload_to='uploadreceipt', verbose_name='Proof of Payment')),
                ('payment_car_reg_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcmappv2.Member')),
            ],
        ),
        migrations.AddField(
            model_name='car',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pcmappv2.Member'),
        ),
    ]
