# Generated by Django 2.1 on 2018-08-24 13:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_receipt_image',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploadreceipt', verbose_name='Proof of Payment'),
            preserve_default=False,
        ),
    ]
