# Generated by Django 2.1 on 2018-09-04 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='member_id',
        ),
        migrations.RemoveField(
            model_name='member',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_car_reg_no',
        ),
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.DeleteModel(
            name='Member',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
