# Generated by Django 2.1 on 2018-08-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0003_remove_car_car_engine_chasis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(choices=[('2008', '2008'), ('206', '206'), ('206 CC', '206 CC'), ('207', '207'), ('207 CC', '207 CC'), ('208', '208'), ('208 GTi', '208 GTi'), ('3008', '3008'), ('306', '306'), ('307', '307'), ('308', '308'), ('308 CC', '308 CC'), ('405', '405'), ('406', '406'), ('407', '407'), ('408', '408'), ('5008', '5008'), ('504', '504'), ('508', '508'), ('508 SW', '508 SW'), ('807', '807'), ('Partner', 'Partner'), ('RCZ', 'RCZ'), ('Traveller', 'Traveller')], max_length=20, verbose_name='Model'),
        ),
    ]
