# Generated by Django 2.1 on 2018-09-09 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0002_auto_20180909_1503'),
        ('pcmappv2', '0003_auto_20180904_1001'),
    ]

    operations = [
    ]
