# Generated by Django 2.1 on 2018-09-11 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0004_merge_20180909_1612'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.CharField(max_length=50, verbose_name='Event title')),
                ('activity_date', models.DateField(verbose_name='Event date')),
                ('activity_venue', models.CharField(max_length=100, verbose_name='Event location')),
                ('activity_description', models.CharField(max_length=500, verbose_name='Event description')),
                ('activity_link_fb', models.URLField(blank=True, null=True, verbose_name='FB URL')),
                ('activity_link_ig', models.URLField(blank=True, null=True, verbose_name='IG URL')),
                ('activity_create_date', models.DateTimeField()),
                ('activity_image', models.FileField(upload_to='static/images', verbose_name='Upload image')),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-activity_date'],
            },
        ),
    ]
