# Generated by Django 2.1 on 2018-08-25 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0004_auto_20180825_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_pdpa_accepted',
            field=models.BooleanField(default=False, verbose_name='By clicking the box you agree to the PCM PDPA policy.'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_model',
            field=models.CharField(choices=[('2008', '2008'), ('206', '206'), ('206 CC', '206 CC'), ('207 Sedan', '207 Sedan'), ('207 CC', '207 CC'), ('208', '208'), ('208 GTi', '208 GTi'), ('3008', '3008'), ('305', '305'), ('306', '306'), ('307', '307'), ('307 SW', '307 SW'), ('308', '308'), ('308 CC', '308 CC'), ('405', '405'), ('406', '406'), ('407', '407'), ('407 SW', '407 SW'), ('408', '408'), ('5008', '5008'), ('504', '504'), ('505', '505'), ('508', '508'), ('508 SW', '508 SW'), ('607', '607'), ('807', '807'), ('Partner', 'Partner'), ('RCZ', 'RCZ'), ('Traveller', 'Traveller')], max_length=20, verbose_name='Model'),
        ),
    ]
