# Generated by Django 2.1 on 2018-08-25 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0005_auto_20180826_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='member_pdpa_accepted',
            field=models.BooleanField(default=False, verbose_name='By selecting "Yes" you agree to the PCM PDPA policy.'),
        ),
    ]
