# Generated by Django 2.1 on 2018-09-11 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0005_activity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['member_name']},
        ),
    ]
