# Generated by Django 2.1 on 2018-08-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0006_auto_20180826_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member_status',
            field=models.BooleanField(default=True, verbose_name='Status'),
        ),
    ]
