# Generated by Django 2.0.6 on 2018-09-03 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0007_member_member_status'),
        ('pcmappv2', '0002_auto_20180904_0032'),
    ]

    operations = [
    ]
