# Generated by Django 2.1 on 2020-04-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcmappv2', '0007_auto_20180926_0018'),
        ('pcmappv2', '0003_auto_20190417_1440'),
    ]

    operations = [
    ]
