# Generated by Django 2.1 on 2020-04-06 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pcmappv2', '0008_merge_20200406_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Admin User'),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_updated_date',
            field=models.DateField(blank=True, null=True, verbose_name='Admin updated date'),
        ),
    ]
